import { UnifiedJointName } from '@/types/pose';

export const MIXAMO_BONES = {
  HIPS: 'mixamorig:Hips',
  SPINE: 'mixamorig:Spine',
  SPINE1: 'mixamorig:Spine1',
  SPINE2: 'mixamorig:Spine2',
  NECK: 'mixamorig:Neck',
  HEAD: 'mixamorig:Head',
  RIGHT_SHOULDER: 'mixamorig:RightShoulder',
  RIGHT_ARM: 'mixamorig:RightArm',
  RIGHT_FOREARM: 'mixamorig:RightForeArm',
  RIGHT_HAND: 'mixamorig:RightHand',
  LEFT_SHOULDER: 'mixamorig:LeftShoulder',
  LEFT_ARM: 'mixamorig:LeftArm',
  LEFT_FOREARM: 'mixamorig:LeftForeArm',
  LEFT_HAND: 'mixamorig:LeftHand',
  RIGHT_UP_LEG: 'mixamorig:RightUpLeg',
  RIGHT_LEG: 'mixamorig:RightLeg',
  RIGHT_FOOT: 'mixamorig:RightFoot',
  RIGHT_TOE_BASE: 'mixamorig:RightToeBase',
  LEFT_UP_LEG: 'mixamorig:LeftUpLeg',
  LEFT_LEG: 'mixamorig:LeftLeg',
  LEFT_FOOT: 'mixamorig:LeftFoot',
  LEFT_TOE_BASE: 'mixamorig:LeftToeBase',
  RIGHT_THUMB_1: 'mixamorig:RightHandThumb1',
  RIGHT_INDEX_1: 'mixamorig:RightHandIndex1',
  RIGHT_PINKY_1: 'mixamorig:RightHandPinky1',
  LEFT_THUMB_1: 'mixamorig:LeftHandThumb1',
  LEFT_INDEX_1: 'mixamorig:LeftHandIndex1',
  LEFT_PINKY_1: 'mixamorig:LeftHandPinky1',
} as const;

export type MixamoBoneName = typeof MIXAMO_BONES[keyof typeof MIXAMO_BONES];

export const JOINT_TO_BONE_MAP: Partial<Record<UnifiedJointName, MixamoBoneName>> = {
  hipCentre: MIXAMO_BONES.HIPS,
  neck: MIXAMO_BONES.NECK,
  rightShoulder: MIXAMO_BONES.RIGHT_ARM,
  rightElbow: MIXAMO_BONES.RIGHT_FOREARM,
  rightWrist: MIXAMO_BONES.RIGHT_HAND,
  rightThumb: MIXAMO_BONES.RIGHT_THUMB_1,
  rightIndex: MIXAMO_BONES.RIGHT_INDEX_1,
  rightPinky: MIXAMO_BONES.RIGHT_PINKY_1,
  leftShoulder: MIXAMO_BONES.LEFT_ARM,
  leftElbow: MIXAMO_BONES.LEFT_FOREARM,
  leftWrist: MIXAMO_BONES.LEFT_HAND,
  leftThumb: MIXAMO_BONES.LEFT_THUMB_1,
  leftIndex: MIXAMO_BONES.LEFT_INDEX_1,
  leftPinky: MIXAMO_BONES.LEFT_PINKY_1,
  rightHip: MIXAMO_BONES.RIGHT_UP_LEG,
  rightKnee: MIXAMO_BONES.RIGHT_LEG,
  rightAnkle: MIXAMO_BONES.RIGHT_FOOT,
  rightToe: MIXAMO_BONES.RIGHT_TOE_BASE,
  leftHip: MIXAMO_BONES.LEFT_UP_LEG,
  leftKnee: MIXAMO_BONES.LEFT_LEG,
  leftAnkle: MIXAMO_BONES.LEFT_FOOT,
  leftToe: MIXAMO_BONES.LEFT_TOE_BASE,
};
