import { UnifiedJointName } from '@/types/pose';

export const MIXAMO_BONES = {
  HIPS: 'mixamorigHips',
  SPINE: 'mixamorigSpine',
  SPINE1: 'mixamorigSpine1',
  SPINE2: 'mixamorigSpine2',
  NECK: 'mixamorigNeck',
  HEAD: 'mixamorigHead',
  RIGHT_SHOULDER: 'mixamorigRightShoulder',
  RIGHT_ARM: 'mixamorigRightArm',
  RIGHT_FOREARM: 'mixamorigRightForeArm',
  RIGHT_HAND: 'mixamorigRightHand',
  LEFT_SHOULDER: 'mixamorigLeftShoulder',
  LEFT_ARM: 'mixamorigLeftArm',
  LEFT_FOREARM: 'mixamorigLeftForeArm',
  LEFT_HAND: 'mixamorigLeftHand',
  RIGHT_UP_LEG: 'mixamorigRightUpLeg',
  RIGHT_LEG: 'mixamorigRightLeg',
  RIGHT_FOOT: 'mixamorigRightFoot',
  RIGHT_TOE_BASE: 'mixamorigRightToeBase',
  LEFT_UP_LEG: 'mixamorigLeftUpLeg',
  LEFT_LEG: 'mixamorigLeftLeg',
  LEFT_FOOT: 'mixamorigLeftFoot',
  LEFT_TOE_BASE: 'mixamorigLeftToeBase',
  RIGHT_THUMB_1: 'mixamorigRightHandThumb1',
  RIGHT_INDEX_1: 'mixamorigRightHandIndex1',
  RIGHT_PINKY_1: 'mixamorigRightHandPinky1',
  LEFT_THUMB_1: 'mixamorigLeftHandThumb1',
  LEFT_INDEX_1: 'mixamorigLeftHandIndex1',
  LEFT_PINKY_1: 'mixamorigLeftHandPinky1',
} as const;

export type MixamoBoneName = typeof MIXAMO_BONES[keyof typeof MIXAMO_BONES];

export const JOINT_TO_BONE_MAP: Partial<Record<UnifiedJointName, MixamoBoneName>> = {
  hipCentre: MIXAMO_BONES.HIPS,
  neck: MIXAMO_BONES.NECK,
  rightShoulder: MIXAMO_BONES.RIGHT_ARM,
  rightElbow: MIXAMO_BONES.RIGHT_FOREARM,
  rightWrist: MIXAMO_BONES.RIGHT_HAND,
  rightThumb: MIXAMO_BONES.RIGHT_THUMB_1,
  rightIndex: MIXAMO_BONES.RIGHT_INDEX_1,
  rightPinky: MIXAMO_BONES.RIGHT_PINKY_1,
  leftShoulder: MIXAMO_BONES.LEFT_ARM,
  leftElbow: MIXAMO_BONES.LEFT_FOREARM,
  leftWrist: MIXAMO_BONES.LEFT_HAND,
  leftThumb: MIXAMO_BONES.LEFT_THUMB_1,
  leftIndex: MIXAMO_BONES.LEFT_INDEX_1,
  leftPinky: MIXAMO_BONES.LEFT_PINKY_1,
  rightHip: MIXAMO_BONES.RIGHT_UP_LEG,
  rightKnee: MIXAMO_BONES.RIGHT_LEG,
  rightAnkle: MIXAMO_BONES.RIGHT_FOOT,
  rightToe: MIXAMO_BONES.RIGHT_TOE_BASE,
  leftHip: MIXAMO_BONES.LEFT_UP_LEG,
  leftKnee: MIXAMO_BONES.LEFT_LEG,
  leftAnkle: MIXAMO_BONES.LEFT_FOOT,
  leftToe: MIXAMO_BONES.LEFT_TOE_BASE,
};
